allowBuilds:
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - esbuild
  - sharp
